// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvetboekyihvcialyeai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZXRib2VreWlodmNpYWx5ZWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mzg3NTEsImV4cCI6MjA3MjMxNDc1MX0.SsxcBq7rfYRNXwHFzxPzXYPcokLdKEoarCsxWcdWSKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});